### PR TITLE
Clarity UI

### PR DESCRIPTION
**Pull request by vinayvivekananda**
Addressed review comments from https://github.com/TheNewStellW/vmware-operations-guide/pull/16

1. Italicised text is substantially smaller than it's surrounding text. Additionally, any existing formatting due to the header (bold) is ignored
2. Bullet points are not indenting at the first level. I imagine this is a CSS issue too
image

5. Images don't 'explode' when clicked.
6 Table header text has no space/buffer from the table.
7 Table of contents button is missing from the breadcrumbs
Why is this required. I do not see it working. I have left it as it is.

### CODE REVIEW

**Comment by TheNewStellW** [comment]
- [X] ~~1. Italicised text is substantially smaller than it's surrounding text.~~
- [X] ~~2. Bullet points are not indenting at the first level. I imagine this is a CSS issue too~~
- [ ] 3. Footnote links are not working. Not sure why that is.
- [ ] 4. Clicking the callback link in a footnote does not take the user to the point of call
- [X] ~~5. Images don't 'explode' when clicked.~~
- [X] ~~6. Table header text has no space/buffer from the table.~~
- [ ] 7. Table of contents button is missing from the breadcrumbs
- [ ] 8. If a header is followed immediately by bullets, then no spacing is including after the header


Looking great so far @vinayvivekananda !

**Comment by vinayvivekananda** [comment]
3 and 4 done

**Comment by vinayvivekananda** [comment]
7.  Why do we need "Table of contents button"? what is the use.. I did not get it. If it's function is useful only for smaller screen. it is taken care of. Table of contents button is visible only in smaller screens.
Screenshot 2021-09-08 at 5 44 27 PM

**Comment by vinayvivekananda** [comment]
8. done.

**Comment by vinayvivekananda** [comment]
You can rebase to single commit before merging to main.

**Comment by TheNewStellW** [comment]
Great stuff Vinay! I checked over the footnotes issue, and while it is shifting users to the footnote block, clicking any callbacks takes them to the 1st footnote regardless of which one they clicked. Example: /operations-management/chapter-1-overview/1.1.4-begin-with-the-end-in-mind

**Comment by TheNewStellW** [comment]
For the table of contents (issue 7), this is what's missing:

image

On mouse over the table of contents for the page itself is displayed enumerating all headers and indenting based on header size: 

image

The mobile view shows the navigation menu pull out, but not the on-page TOC

**Comment by vinayvivekananda** [comment]
Interesting "Table of contents" on mouseover is not visible for me even in https://www.vmwareopsguide.com/

**Comment by vinayvivekananda** [comment]
Fixed Scroll to footnote and back.

**Comment by vinayvivekananda** [comment]
Added Table of Contents and Made search full width

**Comment by vinayvivekananda** [comment]
> * [x]  1. Italicised text is substantially smaller than it's surrounding text.~
> * [x]  2. Bullet points are not indenting at the first level. I imagine this is a CSS issue too~
> * [x]  3. Footnote links are not working. Not sure why that is.
> * [x]  4. Clicking the callback link in a footnote does not take the user to the point of call
> * [x]  5. Images don't 'explode' when clicked.~
> * [x]  6. Table header text has no space/buffer from the table.~
> * [x]  7. Table of contents button is missing from the breadcrumbs
> * [x]  8. If a header is followed immediately by bullets, then no spacing is including after the header

Additionally Made Search bar full width

Play around here.. https://vinayvivekananda.github.io/vmware-operations-guide/

**Review by TheNewStellW — APPROVED** [review]
Approving all changes except the github workflow file.

**Comment by TheNewStellW** [comment]
Squashing the changes due to majority of theme work being done under a new sub-module (https://github.com/vinayvivekananda/hugo-theme-clarity-learn). Leaving full history in commit log.

**Pull request merged**
